toolbar:
  - styleselect | bold italic | bullist numlist outdent indent | undo redo | image link
  - fontsizeselect | alignleft aligncenter alignright | forecolor backcolor
fontsize_formats:
  - 8pt 10pt 12pt 14pt 18pt 24pt 36pt
plugins:
  - image
  - link
  - textcolor
